"""Compute and time for the v2 production run (camera-ready compute table).

Measured values come from frozen receipts: the normalization completion record, the 128
render-shard summaries, and the LoMa-R/RoMa v2 shard runtimes that match-expand's census
summed from the frozen shard summaries. Values recorded only in the progress log (SAM 3.1
GPU time, Gemini batch cost) are passed in the config with their citation and labelled.

    python -m ecad_paper_figures.compute_table --config configs/camera_ready_compute_v2.json \
        --output $ECAD_RUNS/paper-cr-compute-v1
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from .cr_common import code_revision, promote, verify_inputs, write_json, write_macros

VERSION = "paper-cr-compute-table/v1"


def compute(config: dict[str, Any]) -> dict[str, Any]:
    inputs = config["inputs"]
    completion = json.loads(Path(inputs["normalization_baseline_completion"]["path"]).read_text())
    census = json.loads(Path(inputs["match_census_summary"]["path"]).read_text())
    shards = [
        json.loads(Path(spec["path"]).read_text())
        for name, spec in sorted(inputs.items())
        if name.startswith("render_shard_")
    ]
    if len(shards) != config["expected_render_shards"]:
        raise ValueError(f"expected {config['expected_render_shards']} render shards, got {len(shards)}")
    units = census["unit_costs_from_frozen_shard_summaries"]
    rows = {
        "normalization_cpu_hours": completion["normalization"]["total_item_runtime_seconds"] / 3600,
        "normalization_items": completion["normalization"]["unique_contents_attempted"],
        "render_cpu_hours": sum(s["runtime_seconds"] for s in shards) / 3600,
        "render_items": sum(s["planned"] for s in shards),
        "loma_feature_gpu_hours": units["loma_features"]["seconds"] / 3600,
        "loma_feature_items": int(units["loma_features"]["units"]),
        "loma_match_gpu_hours": units["loma_attempts"]["seconds"] / 3600,
        "roma_gpu_hours": units["roma_attempts"]["seconds"] / 3600,
        "matched_pairs": int(units["roma_attempts"]["units"]),
        "sam_gpu_hours": config["logged"]["sam_gpu_hours"]["value"],
        "vlm_calls": config["logged"]["vlm_calls"]["value"],
        "vlm_cost_usd": config["logged"]["vlm_cost_usd"]["value"],
    }
    rows["gpu_hours_total"] = (
        rows["loma_feature_gpu_hours"] + rows["loma_match_gpu_hours"] + rows["roma_gpu_hours"] + rows["sam_gpu_hours"]
    )
    return rows


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    config = json.loads(args.config.read_text())
    verified = verify_inputs(config["inputs"])
    request = {"schema_version": VERSION, "config_name": config["name"], "inputs": verified, "logged": config["logged"]}

    def build(tmp: Path) -> dict[str, Any]:
        rows = compute(config)
        write_json(tmp / "compute.json", rows)
        fmt = lambda v: f"{v:.1f}"  # noqa: E731
        write_macros(tmp / "numbers_compute.tex", {
            "fCpuHoursNormalization": fmt(rows["normalization_cpu_hours"]),
            "fCpuHoursRender": fmt(rows["render_cpu_hours"]),
            "fGpuHoursSam": fmt(rows["sam_gpu_hours"]),
            "fGpuHoursLomaFeatures": fmt(rows["loma_feature_gpu_hours"]),
            "fGpuHoursLomaMatching": fmt(rows["loma_match_gpu_hours"]),
            "fGpuHoursRoma": fmt(rows["roma_gpu_hours"]),
            "fGpuHoursTotal": fmt(rows["gpu_hours_total"]),
            "nLomaFeatureImages": f"{rows['loma_feature_items']:,}",
            "nVlmCalls": f"{rows['vlm_calls']:,}",
            "fVlmCostUsd": f"\\${rows['vlm_cost_usd']:.2f}",
        }, f"Generated by {VERSION} (config {config['name']}).")
        return {"code_revision": code_revision(Path(__file__).parent), "rows": rows, "schema_version": VERSION}

    print(json.dumps(promote(args.output, request, build), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
